### ISSUE TITLE
Sending pictures (attachments) to Android device does not work

### ISSUE THREAD

**Issue by dansroot** [loki-project/session-ios#128]
Testing the latest Session release with various devices. Sending pictures from iPhone or Mac (same account) to an Android device did not work within several attempts. Pictures seem to be sent on the sending device, but are not received by the target device (only a black frame is displayed). Sending pictures from the same iPhone to another iPhone recipient did work. Please check. Thanks!

**Comment by nielsandriesse** [comment]
This shouldn't be an issue anymore
