### ISSUE TITLE
The Private issues

### ISSUE THREAD

**Issue by isharrrry** [loki-project/session-ios#136]
**Describe the bug**
Very insufficient privacy, can not get the installation package .ipa file freely, it was known by the Apple Store that I installed

**To reproduce**
Download

**Screenshots or logs**
...

**Smartphone (please complete the following information):**
 - Device:   iPhone 6 
 - OS:   iOS 8.1 

**Additional context**

**Comment by KeeJef** [comment]
An IPA has been added to the Github releases page, we will make sure to do this in future releases too
