### ISSUE TITLE
problems since 1.0.6

### ISSUE THREAD

**Issue by boistordu** [loki-project/session-ios#137]
since 1.0.6 update from today on ios, no messages goes through in note to self and so the sync with session-desktop on windows doesn't work from ios to PC.
it works from PC to IOS but when the message is  landing on the ios device the device crashes.

Long time also at encrypting the message and tracing a path steps.
Maybe it's just temporary

**Comment by Mikunj** [comment]
Which of the device is the primary and which is the secondary?

**Comment by nielsandriesse** [comment]
Closing this as it no longer seems relevant.
