### ISSUE TITLE
Notifications out of the app does not say when you have a message 

### ISSUE THREAD

**Issue by Neku3721** [loki-project/session-ios#140]
Notifications out of the app does not say when you have a message.

Must open the app and select a contact. Write to a contact. Even if the contact answer you and if the app is closed, you will not have the notifications.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: iPhone 7+
 - OS: 13.3.1
 - Session version 1.0.6

**Additional context**

**Comment by gmbnt** [comment]
We're working on fixing this.

**Comment by nielsandriesse** [comment]
This shouldn't be an issue anymore now that we use APNs
