### ISSUE TITLE
Join open group fails

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-ios#146]
**Describe the bug**
Mobile can't join current version of open group server. Desktop is fine.

Going over the server logs: iOS seems to be using an invalid token and not refreshing the token. Server is returning a 403 for ` GET /channels/1`

I can hack around the 'invalid token' to pass the /channels/1 check but mobile still continues to send an invalid token, even after that. Even if I return a 401 instead of a 403.

Also I've seen requests to `//loki/v1/get_challenge` which are not (/no longer) valid but even if I patch up the server to support them, iOS still can't join

Android seems to also have the same behavior.

I just can't prompt iOS to get a proper/correct token

Will update issue as I learn more.

**To reproduce**
try joining https://indonesiainklusi.getsession.org/ after I whitelist your SessionID

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: iPhone7+ (Sam has 7+ too)
 - OS: 12.4 (and w/e Sam is using, he says latest iOS)
 - Version of Session or latest commit hash: 1.0.8 (64)

**Additional context**

**Comment by neuroscr** [comment]
also iOS performance when getting 401/403s in the background continuously seems horrible, I can barely reply in a different open group

**Comment by nielsandriesse** [comment]
I believe this has been fixed
