### ISSUE TITLE
Entering 25 word seed crashes Session and can't re-open without crash

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-ios#150]
**Describe the bug**

**To reproduce**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: iphone 7+
 - OS: iOS 12.4
 - Version of Loki Messenger or latest commit hash: 1.0.8 (64)

**Additional context**

**Comment by nielsandriesse** [comment]
This isn't a bug. 25 word seeds are no longer supported.
