### ISSUE TITLE
iOS sends an empty message after accepting Desktop friend request

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-ios#159]
**Describe the bug**

When an iOS device accepts a friend request from a Desktop device, it sends an empty message to the Desktop device.

**To reproduce**
Desktop device sends a friend request to iOS device
iOS device receives the requests and accepts it
Desktop device receives an empty message from iOS device

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
<img width="729" alt="Screen Shot 2020-04-15 at 12 06 31 pm" src="https://user-images.githubusercontent.com/62363622/79416560-4931c380-7ff3-11ea-9937-0f0024161852.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 8Plus / Desktop PC or Mac
 - OS: iOS 13.4.1 / Desktop Windows or MacOS
 - Version of Loki Messenger or latest commit hash:
iOS: c596d5b2a3703c5a16a7268962d4d31ee84acbc2
Desktop: 85e5a067c98a02267034d99fb3622d68b53de609

**Additional context**

**Comment by nielsandriesse** [comment]
This is actually a desktop side issue. Desktop needs to hide messages without text.

**Comment by Mikunj** [comment]
Hmm, it may or may not be. I recall we wither looking to change / changing background messages to not use empty text so we might need to update it on iOS too

**Comment by nielsandriesse** [comment]
We could do that too. The original reason for using an empty string and not `null` was simply that the Signal message sending and receiving pipelines don't like `null` :)
