### ISSUE TITLE
Messages from secondary iOS device appear twice in primary device

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-ios#167]
**Describe the bug**

When I write in a closed group with an iOS secondary device, the message appears twice in the primary device: once on the left part of the conversation, one on the right part.
The primary device can be either Desktop or iOS. No issue with Android.

**To reproduce**

Starting with a Desktop or iOS Primary device with at least one closed group.
Pairing an iOS device to the primary device.
When the groups are loaded, writing in one of the closed groups.
The message will display twice in the primary device.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.
<img width="737" alt="Screen Shot 2020-04-28 at 9 48 24 am" src="https://user-images.githubusercontent.com/62363622/80432009-5bd2c380-8936-11ea-9e67-315e89598b94.png">

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4.1
 - Version of Session or latest commit hash:
iOS -> 8b50cca7bd4ae2cd60f451737028204149f1e2d2
Desktop -> 1a0b760fa15c59e0ca996304d35ac9b6d986f530

**Additional context**

**Comment by nielsandriesse** [comment]
This should now be fixed
