### ISSUE TITLE
Possible to pair two devices

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-ios#168]
**Describe the bug**

With iOS as primary device, if I repeat the pairing device process directly after accepting a pairing request, I can pair an other device.

**To reproduce**

On an iOS (primary) device, start the pairing device process with a secondary device. After accepting the pairing request, it is possible to quickly click on the ‘Link a device’ button again and start the pairing process with a second device.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.
<img width="418" alt="Screen Shot 2020-04-27 at 5 06 50 pm" src="https://user-images.githubusercontent.com/62363622/80432658-39da4080-8938-11ea-984d-6df3774edd28.png">

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4.1
 - Version of Session or latest commit hash: 8b50cca7bd4ae2cd60f451737028204149f1e2d2

**Additional context**

**Comment by nielsandriesse** [comment]
This should now be fixed
