### ISSUE TITLE
Issue when sending a friend request after trying to pair with a device

### ISSUE THREAD

**Issue by Brice-W** [loki-project/session-ios#171]
**Describe the bug**

A = iOS device
B = any platform
If I try to pair A to B and then cancel pairing and create a new session ID with A, I can’t message B, it shows ‘Pending session request’ and it’s not possible to send a friend request.

**To reproduce**

A tries to pair with B while B is not in pairing mode.
B receives a notification that someone is trying to pair.
A cancels pairing.
Then A creates a session ID and wants to send a friend request to B.
A scan B QR code or enters its ID, it opens a new conversation, the text area is blocked and shows ‘Pending session request’.
No request is received on B.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4.1
 - Version of Session or latest commit hash: 8b50cca7bd4ae2cd60f451737028204149f1e2d2

**Additional context**

**Comment by nielsandriesse** [comment]
This should now be fixed
