### ISSUE TITLE
Multiple prompts and crash sending picture first time

### ISSUE THREAD

**Issue by james-culp** [loki-project/session-ios#206]
**Describe the bug**

When sending a picture (taken from camera, not library) to a contact, I received multiple prompts and a crash. This was the first time I'd tried it in Session.

**To reproduce**

1. Click button to take a picture
2. Receive permissions prompt to grant access to camera, accept
3. Take picture
4. Receive permissions prompt to grant access to photo library &larr; This seems like a bug on its own
5. Session crashes in background &larr; Clearly a bug
6. Accept permissions
7. Restart Session, do everything again, works OK

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro
 - OS: iOS 13.5
 - Version of Session: 1.2.3

**Additional context**

**Comment by nielsandriesse** [comment]
This has been fixed :) .
