### ISSUE TITLE
Icon for muted not clearing after expiry

### ISSUE THREAD

**Issue by darcys22** [loki-project/session-ios#219]
**Describe the bug**
The icon for a chat being muted still appears after the time has expired.
Todays date is june 27 however the chat is ‘muted until may 1’

**To reproduce**

- Mute a chat temporarily
- Let timeframe for mute expire
- notification for mute still appear. Settings for the chat say not muted.

**Smartphone (please complete the following information):**

 - Device: iphone X
 - OS: 13.5.1
 - Version of Session or latest commit hash: IOS session 1.2.5

Screenshots

![83DC83A0-021D-4521-8A38-1006231E567D](https://user-images.githubusercontent.com/2188604/85903773-8237b100-b84a-11ea-8ea5-8744e7ab3736.jpeg)

![1AD5FDE6-57C7-4679-AC90-C2B2CCAFC5B2](https://user-images.githubusercontent.com/2188604/85903795-8ebc0980-b84a-11ea-9474-e39ec437e416.jpeg)

**Comment by Brice-W** [comment]
This issue has been fixed
