### ISSUE TITLE
App switch preview does not respect dark mode

### ISSUE THREAD

**Issue by james-culp** [loki-project/session-ios#263]
**Describe the bug**

When I have dark mode enabled in Session, and I have app preview disabled in Session, I still see a white screen when I go to the iOS app switcher. 

**To reproduce**

- Enable dark mode
- Disable app switch preview 
- Pull up from bottom of screen to go to app switcher
- App preview is a placeholder as expected, but white, not dark 

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro
 - OS: 13.7
 - Version of Session: 1.5.1

**Additional context**

**Comment by nielsandriesse** [comment]
This is actually due to an iOS limitation. It can take quite a bit of time for the preview to update after you've switched to dark mode.
