### ISSUE TITLE
Voice messages do not show up in "All Media"

### ISSUE THREAD

**Issue by eharris** [loki-project/session-ios#282]
**Describe the bug**

Received voice messages do not show up in "All Media" page under the conversation.

**To reproduce**

Have someone send you a voice recording.  Observe that it doesn't show up in "All Media"

**Smartphone (please complete the following information):**

 - Device: iPhone 7 Plus
 - OS: iOS 13.3
 - Version: 1.5.3

**Comment by nielsandriesse** [comment]
This is actually by design. The All Media screen is just meant for pictures and videos. Maybe we should call it something else :) .

**Comment by eharris** [comment]
Recordings are still media.  Why should recordings be excluded from "media"?
