### ISSUE TITLE
Deleting all messages for a contact?

### ISSUE THREAD

**Issue by 097115** [loki-project/session-ios#322]
With the desktop (macOS) version, I can delete all the messages for a contact with the right click on the conversation and then selecting "Delete messages". However, with Session for iOS, I can't find this function. Is it possible?

### Device info

**Device**: iPhone 6 (so, no 3D Touch in case it's there :)

**iOS version**: iOS 12.4.9

**Session version:** 1.7.3 (158)

**Comment by nielsandriesse** [comment]
You can do this by swiping on the conversation and pressing delete. This'll delete the conversation and all the messages in it.

**Comment by 097115** [comment]
@nielsandriesse It's not the same though, isn't it? 

**Deleting the conversation** will also delete the contact, and in order to keep chatting with this person, you'll have to add them again (meaning getting / enter their Session ID and everything.) While **deleting messages** on the desktop doesn't have such consequences.

So, I don't know, these two certainly doesn't seem equivalent to me, and may be it's worth to re-open the issue? :)
