### ISSUE TITLE
Iphone x no notification displayed except icon badge

### ISSUE THREAD

**Issue by dcutugno** [loki-project/session-ios#48]
**Describe the bug**
On my iphone X IOS 12.4.1 no notifications and sound are displayed except the badge with numbers on messenger icon, so i can't see if new messages are incoming i have to go to the page where icon is and check if a new number is displayed

**To reproduce**
always

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 12.4.1
 - Version of Loki Messenger 1.1.0

**Comment by gmbnt** [comment]
This is a known issue that'll occur until we have full Lokinet integration. Right now the app occasionally polls in the background but it's very unreliable.
