### ISSUE TITLE
Microphone flashes when sending image

### ISSUE THREAD

**Issue by KeeJef** [loki-project/session-ios#85]
**Describe the bug**

After sending an image on iOS the microphone flashes as if it was being used, we are not actually using the microphone for anything here 

**To reproduce**

take an image and upload to chat

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 6]
 - OS: [e.g. iOS 8.1]
 - Version of Loki Messenger or latest commit hash

**Additional context**

**Comment by gmbnt** [comment]
This has been fixed.
