### ISSUE TITLE
Various bugs/UI issues

### ISSUE THREAD

**Issue by Prophet-26** [loki-project/session-ios#90]
1.) Some GIFs fail to send while some send with no problem. Perhaps a size limitation?

2.) GIF metadata warning message should be present for the first time you send a GIF, not every time. Perhaps a tick box “Do not show this message again” can be useful.

3.) Profile picture should be displayed at the top of a Session/Group chat to the left of the Name. 

4.) Original message not found error when the original message is clearly still visible. Screenshot 1.

5.) If you mute a session/group it shouldn’t permanently say that it is muted under the group name. That space should be reserved for group information such as member count. It looks very cluttered and the muted microphone icon is indication enough. Screenshot 2.

6.) Old Loki messenger icon displayed above session when it is in the app tray. Screenshot 3.

![40BC3552-9D24-4786-8E96-2FB551588842](https://user-images.githubusercontent.com/60772777/74011081-99efc500-498f-11ea-81f9-1f115de0a186.png)
![5E417E80-ECC6-493E-8C66-D37558A3A1D4](https://user-images.githubusercontent.com/60772777/74011088-9ceab580-498f-11ea-9a3a-3673d2d999c8.png)
![B61062C8-B0C3-42EF-828B-BD8A613FC568](https://user-images.githubusercontent.com/60772777/74011089-9ceab580-498f-11ea-81f6-e725d7e35f73.jpeg)

**Comment by Prophet-26** [comment]
7.) Read receipts are only visible when in the  conversation list and not inside the Session.

8.) The user should be able to access the recipient profile/group info by clicking on the Name at the top of the conversation. Should also be able to enlarge the profile picture of the  recipient/group by clicking on it.

**Comment by Prophet-26** [comment]
8.) 8.) Swipe to reply. 
9.) If a GIF is the last message of a conversation the text input bar cuts off the bottom bit of the GIF.
10.) When you have multiple unread messages in a group there should be an indicator of how many unread messages there are. This indicator should be visible in the conversation list screen and within the group. Telegram is a good comparison.
11.) On the open group page there should be a button that says “How to host your own open group” that will display step by step instructions when you click on it. Alternatively link to GH instructions. o host your own open group” that will display step by step instructions when you click on it. Alternatively link to GH instructions.

**Comment by nielsandriesse** [comment]
Most of this has been addressed. The rest is on the roadmap. Closing this for now.
