### ISSUE TITLE
App Frozen Upon Re-Opening

### ISSUE THREAD

**Issue by Skelaton4** [loki-project/session-ios#91]
**Describe the bug**
App freezes after re-opening on first launch. 

**To reproduce**
Close iOS app and open it. 

**Screenshots or logs**
![2020-02-07](https://user-images.githubusercontent.com/28955674/74057609-4d69b100-49b2-11ea-8ea7-b0280e95a450.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: OS 13.3.1
 - Version of Loki Messenger or latest commit hash

**Additional context**

**Comment by gmbnt** [comment]
This has been fixed. Will be rolled out with the 1.0.3 release.
