### ISSUE TITLE
Seed word killed Session's ability to start

### ISSUE THREAD

**Issue by neuroscr** [loki-project/session-ios#97]
**Describe the bug**
Restored from twenty five word seed, and now the app won't open

**Smartphone (please complete the following information):**
 - Device: iPhone7+
 - OS: 12.4
 - Version of Loki Messenger or latest commit hash: 1.0.1

**Additional context**

was messing around with multidevice and was trying to go back to my individual sessionid

**Comment by nielsandriesse** [comment]
25 word seeds are no longer supported.
